### ISSUE TITLE
Error at item.split

### ISSUE THREAD

**Issue by JFGHT** [jblanchette/wc3v#1]
Great work man! I just decided to try it out and this is what happened.

`node wc3v.js --replay=happy-vs-grubby`

TypeError: itemId.split is not a function

https://github.com/jblanchette/wc3v/blob/11def63b2738690df4c0f73392468b3cb03d8606/helpers/utils.js#L71

Should be:

`itemId.value.split...`

Edit:

Ok, my problem was that I was installing deps with yarn and then it was installing last version of w3gjs which it seems to handle data differently.

So might be time to update it? :)

**Comment by jblanchette** [comment]
I'll take a look at latest w3gs, right now my deps look like this:

```
$ npm list
w3gv@0.0.1 C:\Users\JeefSSD\Code\wc3v
`-- w3gjs@1.1.2
  `-- binary-parser@1.4.0
```

Unfortunately a bunch of maps are broken when parsing while some others do great.  I'm getting close to a release and will look to add a test suite that'll show pass/fail on a few 'good maps' 

Besides `happy-vs-grubby` I've been keeping `bnet-ud-vs-orc-2` working as well

Thanks for trying it out!

**Comment by JFGHT** [comment]
Fixed at:

https://github.com/jblanchette/wc3v/commit/7c3da67eeaf22ca4b38c4964585f7c55499de524#diff-a83645ecb801b3f513211d5363237314
